version: "3"

services:
  metrics:
    image: factorialtask
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn factorialtask.wsgi:application -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=factorialtask.settings
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: metrics
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
